# -*- coding: utf-8 -*-
"""Satellite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TLjZJJnI2J1KhNOhNuOOFZkAYHbsGGl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/IITR/Satellite-project/Satellite-train.xlsx")
df.head()

import pandas as pd
import requests
import os
import time


ROOT_DIR = "/content/drive/MyDrive/IITR/Satellite-project/"
EXCEL_FILE_NAME = "Satellite-train.xlsx"

EXCEL_PATH = os.path.join(ROOT_DIR, EXCEL_FILE_NAME)
IMAGE_FOLDER = os.path.join(ROOT_DIR, "images")


os.makedirs(IMAGE_FOLDER, exist_ok=True)


df = pd.read_excel(EXCEL_PATH)


df = df[["lat", "long"]]


for idx, row in df.iterrows():


    image_path = os.path.join(IMAGE_FOLDER, f"{idx}.png")


    if os.path.exists(image_path):
        print(f"Already exists: row {idx}, skipping")
        continue

    lat = row["lat"]
    lon = row["long"]


    if pd.isna(lat) or pd.isna(lon):
        print(f"Skipped row {idx} (missing lat/long)")
        continue

    delta = 0.002  # neighborhood size
    bbox = f"{lon-delta},{lat-delta},{lon+delta},{lat+delta}"

    url = (
        "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export"
        f"?bbox={bbox}"
        "&bboxSR=4326"
        "&size=256,256"
        "&format=png"
        "&f=image"
    )

    try:
        response = requests.get(url, timeout=20)

        if response.status_code == 200:
            with open(image_path, "wb") as f:
                f.write(response.content)
            print(f"Downloaded image for row {idx}")
        else:
            print(f"Failed row {idx} (status {response.status_code})")

    except Exception as e:
        print(f"Error at row {idx}: {e}")

    time.sleep(1)



import pandas as pd
import requests
import os
import time


ROOT_DIR = "/content/drive/MyDrive/IITR/Satellite-project/"
EXCEL_FILE_NAME = "Satellite-test.xlsx"

EXCEL_PATH = os.path.join(ROOT_DIR, EXCEL_FILE_NAME)
IMAGE_FOLDER = os.path.join(ROOT_DIR, "images_test")


os.makedirs(IMAGE_FOLDER, exist_ok=True)


df = pd.read_excel(EXCEL_PATH)


df = df[["lat", "long"]]


for idx, row in df.iterrows():


    image_path = os.path.join(IMAGE_FOLDER, f"{idx}.png")


    if os.path.exists(image_path):
        print(f"Already exists: row {idx}, skipping")
        continue

    lat = row["lat"]
    lon = row["long"]


    if pd.isna(lat) or pd.isna(lon):
        print(f"Skipped row {idx} (missing lat/long)")
        continue

    delta = 0.002  # SAME neighborhood size as train
    bbox = f"{lon-delta},{lat-delta},{lon+delta},{lat+delta}"

    url = (
        "https://services.arcgisonline.com/ArcGIS/rest/services/"
        "World_Imagery/MapServer/export"
        f"?bbox={bbox}"
        "&bboxSR=4326"
        "&size=256,256"
        "&format=png"
        "&f=image"
    )

    try:
        response = requests.get(url, timeout=20)

        if response.status_code == 200:
            with open(image_path, "wb") as f:
                f.write(response.content)
            print(f"Downloaded image for row {idx}")
        else:
            print(f"Failed row {idx} (status {response.status_code})")

    except Exception as e:
        print(f"Error at row {idx}: {e}")

    time.sleep(1)

